mpi:
  - msmpi  # [win]
  - mpich  # [not win]
  - openmpi  # [not win]
target_platform:
  - linux-64      # [linux64]
  - linux-aarch64 # [linux and aarch64]
  - linux-ppc64le # [linux and ppc64le]
  - osx-64        # [osx and x86_64]
  - osx-arm64     # [osx and arm64]
c_stdlib_version: #[not aarch64]
  - 10.15         #[not aarch64]
