mpi:
  - msmpi  # [win]
  - mpich  # [not win]
  - openmpi  # [not win]
target_platform:
  - linux-64
  - linux-aarch64
  - linux-ppc64le
  - osx-64
  - osx-arm64
c_stdlib_version: #[not aarch64]
  - 10.15         #[not aarch64]
